version: '2'
services:
    funeraria-app:
        image: funeraria
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://funeraria-mysql:3306/funeraria?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    funeraria-mysql:
        extends:
            file: mysql.yml
            service: funeraria-mysql
